name: "Style check"
description: "Style check using clang-format"

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      shell: bash
      run: |
        # We only make check, not changes
        # Use the find command with the variable
        PROJECT_PATH=$(pwd)

        echo $PROJECT_PATH

        # The 'tr' command is used to translate or remove characters. In this case, it is used to replace line breaks with spaces.
        # This is useful for converting the list of files from the output of the 'find' command into a single line, which can then be passed to the 'clang-format' command.
        SOURCE_FILES=$(find $PROJECT_PATH/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/lib -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")

        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt

        # 'clang-format' is a tool that automatically formats source code to fit a specific coding style, which is located in a file in this project.
        # This command runs 'clang-format' on the source files.        
        # The '-i' argument causes 'clang-format' to apply the changes directly to the files, rather than simply printing the suggested format to stdout.
        # The output of 'clang-format' is redirected to a file called 'clang-format_errors.txt'. If 'clang-format' finds any formatting errors, it will be written to this file.
        CLANG_COMMAND=$(clang-format -i $SOURCE_FILES) > ${ERROR_FILE_FLAG}

        echo "Running: clang-format -i $SOURCE_FILES"

        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: There are some files that are not formatted correctly"
            exit 1
        else
            echo "All files are formatted correctly. Niiiceee"
            exit 0
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Clang-format errors!!!
        path: $PROJECT_PATH/clang-format_errors.txt
        retention-days: 1
